# Generated by Django 3.1.4 on 2020-12-15 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnum', models.CharField(max_length=70)),
                ('cname', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=70, verbose_name='Nom')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='no', max_length=10, verbose_name='Actif')),
                ('gender', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='', max_length=10, verbose_name='Genre')),
                ('phone', models.IntegerField(verbose_name='Telephone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=70, verbose_name='Nom')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='no', max_length=10, verbose_name='Actif')),
                ('gender', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='', max_length=10, verbose_name='Genre')),
                ('phone', models.IntegerField(verbose_name='Telephone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70)),
                ('sdesc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=70, verbose_name='Nom')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='no', max_length=10, verbose_name='Actif')),
                ('gender', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='', max_length=10, verbose_name='Genre')),
                ('phone', models.IntegerField(verbose_name='Telephone')),
                ('terms', models.CharField(choices=[('1', '1 er trimestre'), ('2', '2 eme trimestre'), ('3', '3 eme trimestre')], default='1', max_length=20, verbose_name='Trimestre')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classe', verbose_name='Classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=70)),
                ('cdesc', models.CharField(max_length=100)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classrooms', to='school.classe')),
                ('professeurs', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_professeurs', to='school.professeur')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classrooms', to='school.section'),
        ),
    ]
