# Generated by Django 3.1.4 on 2020-12-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20201215_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromYear', models.IntegerField(verbose_name='De')),
                ('toYear', models.IntegerField(verbose_name='A')),
            ],
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='terms',
        ),
        migrations.AddField(
            model_name='classe',
            name='terms',
            field=models.CharField(choices=[('1', '1 er trimestre'), ('2', '2 eme trimestre'), ('3', '3 eme trimestre')], default='1', max_length=20, verbose_name='classes_trimestres'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_sections', to='school.section'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_classes', to='school.classe'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='professeurs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='school.professeur'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_classes', to='school.classe', verbose_name='Classe'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1', models.DecimalField(decimal_places=2, max_digits=2)),
                ('note2', models.DecimalField(decimal_places=2, max_digits=2)),
                ('note3', models.DecimalField(decimal_places=2, max_digits=2)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_cours', to='school.cours')),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_etudiants', to='school.etudiant')),
            ],
        ),
    ]
