# Generated by Django 3.1.4 on 2020-12-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20201215_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee',
            name='status',
            field=models.CharField(choices=[('en cours', 'EN COURS'), ('ferme', 'Ferme')], default='en cours', max_length=10, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='gender',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='oui', max_length=10, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='gender',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='status',
            field=models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='oui', max_length=10, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='gender',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='status',
            field=models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='oui', max_length=10, verbose_name='Actif'),
        ),
    ]
