# Generated by Django 3.1.4 on 2020-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20201215_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='note',
            name='note2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='note',
            name='note3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2),
        ),
    ]
