# Generated by Django 3.1.4 on 2020-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20201216_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annee',
            name='status',
        ),
        migrations.AddField(
            model_name='annee',
            name='actif',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='professeurs',
            field=models.ManyToManyField(blank=True, related_name='classes_prof', to='school.Professeur'),
        ),
    ]
