# Generated by Django 3.1.4 on 2020-12-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20201217_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annee',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='professeurs',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='professeurs',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='note',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='note',
            name='etudiants',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
