# Generated by Django 3.1.4 on 2020-12-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0012_auto_20201221_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromYear', models.IntegerField(verbose_name='De')),
                ('toYear', models.IntegerField(verbose_name='A')),
                ('is_actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnum', models.CharField(max_length=70, verbose_name='Nom classe')),
                ('cname', models.CharField(max_length=70, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=70, verbose_name='Nom')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name='Genre')),
                ('adresse', models.CharField(max_length=250)),
                ('phone', models.IntegerField(verbose_name='Telephone')),
                ('num_mat', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('orientation', 'Orienttation'), ('transfert', 'Transfert'), ('cl', 'CL')], default='1', max_length=30, verbose_name='Statut eleve')),
                ('is_actif', models.BooleanField(default=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_classes', to='school.classe', verbose_name='Classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=70, verbose_name='Matiere')),
                ('cdesc', models.CharField(max_length=100, verbose_name='Description')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_classes', to='school.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=70, verbose_name='Nom')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name='Genre')),
                ('adresse', models.CharField(max_length=250)),
                ('phone', models.IntegerField(verbose_name='Telephone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=70, verbose_name='Nom')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name='Genre')),
                ('adresse', models.CharField(max_length=250)),
                ('phone', models.IntegerField(verbose_name='Telephone')),
                ('status', models.CharField(choices=[('contractuel', 'Contractuel'), ('permanent', 'Permanent')], default='1', max_length=30, verbose_name='Statut enseignant')),
                ('is_stranger', models.BooleanField(default=False, verbose_name='Etranger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70, verbose_name='Nom section')),
                ('sdesc', models.CharField(max_length=100, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Moyenne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(choices=[('1', '1 er trimestre'), ('2', '2 eme trimestre'), ('3', '3 eme trimestre')], default='1', max_length=20, verbose_name='classes_trimestres')),
                ('coef', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_cours', to='school.matiere')),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_etudiants', to='school.eleve')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='professeurs',
            field=models.ManyToManyField(blank=True, to='school.Professeur'),
        ),
        migrations.AddField(
            model_name='classe',
            name='professeurs',
            field=models.ManyToManyField(blank=True, to='school.Professeur'),
        ),
        migrations.AddField(
            model_name='classe',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_sections', to='school.section'),
        ),
    ]
