# Generated by Django 3.1.4 on 2020-12-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20201221_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee',
            name='is_actif',
            field=models.BooleanField(verbose_name='Annee en cours'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='is_actif',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='num_mat',
            field=models.CharField(blank=True, max_length=20, verbose_name='N° Matricule'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='adresse',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='adresse',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Telephone'),
        ),
    ]
