# Generated by Django 3.1.4 on 2020-12-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20201221_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum', models.CharField(max_length=30)),
                ('ename', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='eleve',
            name='num_mat',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° Matricule'),
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='classes',
        ),
        migrations.AddField(
            model_name='matiere',
            name='classes',
            field=models.ManyToManyField(blank=True, to='school.Classe'),
        ),
    ]
