# Generated by Django 3.1.4 on 2020-12-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20201221_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='cname',
            field=models.CharField(blank=True, max_length=70, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='cdesc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sdesc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description'),
        ),
    ]
