# Generated by Django 3.1.4 on 2020-12-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20201221_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='cnum',
            field=models.CharField(max_length=70, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='gender',
            field=models.CharField(choices=[('h', 'H'), ('f', 'F')], default='homme', max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='status',
            field=models.CharField(choices=[('O', 'Orienttation'), ('TA', 'Transfert annule'), ('TE', 'Transfert en cours'), ('TF', 'Transfert Finalise'), ('cl', 'CL')], default='1', max_length=30, verbose_name='Statut eleve'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='gender',
            field=models.CharField(choices=[('h', 'H'), ('f', 'F')], default='homme', max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='gender',
            field=models.CharField(choices=[('h', 'H'), ('f', 'F')], default='homme', max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sname',
            field=models.CharField(max_length=70, verbose_name='Section'),
        ),
    ]
