# Generated by Django 3.1.4 on 2020-12-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20201222_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='status',
            field=models.CharField(choices=[('O', 'Orienttation'), ('TE', 'Transfert en cours'), ('TF', 'Transfert finalisé'), ('cl', 'CL')], default='1', max_length=30, verbose_name='Statut eleve'),
        ),
    ]
