# Generated by Django 3.1.4 on 2020-12-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20201222_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee',
            name='classes',
            field=models.ManyToManyField(blank=True, to='school.Classe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='first_name',
            field=models.CharField(max_length=70, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='status',
            field=models.CharField(choices=[('o', 'Orienttation'), ('te', 'Transfert en cours'), ('tf', 'Transfert finalisé'), ('cl', 'CL')], default='1', max_length=30, verbose_name="Type d'inscription"),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='cname',
            field=models.CharField(max_length=70, verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='moyenne',
            name='terms',
            field=models.CharField(choices=[('1', '1 er trim'), ('2', '2 eme trim'), ('3', '3 eme trim')], default='1', max_length=20, verbose_name='classes_trimestres'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=70, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='first_name',
            field=models.CharField(max_length=70, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='status',
            field=models.CharField(choices=[('c', 'Contractuel'), ('p', 'Permanent')], default='1', max_length=30, verbose_name='Statut enseignant'),
        ),
    ]
