# Generated by Django 3.1.4 on 2020-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20201223_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee',
            name='is_actif',
            field=models.BooleanField(verbose_name='Année en cours'),
        ),
    ]
