# Generated by Django 3.1.4 on 2020-12-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20201223_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annee',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='professeurs',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='sections',
        ),
        migrations.DeleteModel(
            name='Ecole',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='professeurs',
        ),
        migrations.RemoveField(
            model_name='moyenne',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='moyenne',
            name='etudiants',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Annee',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='Moyenne',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
