# Generated by Django 3.1.4 on 2020-12-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20201223_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='status',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='num_mat',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° Matricule'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Téléphone'),
        ),
    ]
