# Generated by Django 3.1.4 on 2020-12-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20201223_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annee',
            options={'verbose_name_plural': 'Année Scolaire'},
        ),
        migrations.AlterModelOptions(
            name='ecole',
            options={'verbose_name_plural': 'Ecole LT'},
        ),
    ]
