# Generated by Django 3.1.4 on 2020-12-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20201223_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='eleves',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='professeurs',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='sections',
        ),
        migrations.DeleteModel(
            name='Ecole',
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='annee_scolaire',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='professeurs',
        ),
        migrations.RemoveField(
            model_name='moyenne',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='moyenne',
            name='etudiant',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Annee',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
        migrations.DeleteModel(
            name='Inscription',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='Moyenne',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
