# Generated by Django 3.1.4 on 2020-12-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0028_auto_20201224_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromYear', models.IntegerField(verbose_name='De')),
                ('toYear', models.IntegerField(verbose_name='A')),
                ('is_actif', models.BooleanField(unique=True, verbose_name='Année en cours')),
            ],
            options={
                'verbose_name_plural': 'Année Scolaire',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnum', models.CharField(max_length=70, verbose_name='Classe')),
                ('cname', models.CharField(blank=True, max_length=70, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum', models.CharField(max_length=30)),
                ('ename', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'École LT',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=70, verbose_name='Nom')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('h', 'H'), ('f', 'F')], default='h', max_length=10, verbose_name='Genre')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('num_mat', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° Matricule')),
                ('is_actif', models.BooleanField(default=True, verbose_name='Est actif')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=70, verbose_name='Matière')),
                ('cdesc', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('classes', models.ManyToManyField(blank=True, to='school.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=70, verbose_name='Nom')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('h', 'H'), ('f', 'F')], default='h', max_length=10, verbose_name='Genre')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=70, verbose_name='Nom')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('h', 'H'), ('f', 'F')], default='h', max_length=10, verbose_name='Genre')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('c', 'Contractuel'), ('p', 'Permanent')], default='p', max_length=30, verbose_name='Statut enseignant')),
                ('is_stranger', models.BooleanField(default=False, verbose_name='Etranger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70, verbose_name='Section')),
                ('sdesc', models.CharField(blank=True, max_length=100, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Moyenne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', '1 er trim'), ('2', '2 eme trim'), ('3', '3 eme trim')], default='1', max_length=20)),
                ('coef', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_compo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyenne_eleves', to='school.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyenne_matieres', to='school.matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyenne_professeurs', to='school.professeur')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='professeurs',
            field=models.ManyToManyField(blank=True, to='school.Professeur'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('o', 'Orienttation'), ('te', 'Transfert en cours'), ('tf', 'Transfert finalisé'), ('cl', 'CL')], default='o', max_length=30, verbose_name="Type d'inscription")),
                ('date_inscription', models.DateField()),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.annee')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.eleve')),
            ],
            options={
                'unique_together': {('classe', 'eleve')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='eleves',
            field=models.ManyToManyField(through='school.Inscription', to='school.Eleve'),
        ),
        migrations.AddField(
            model_name='classe',
            name='professeurs',
            field=models.ManyToManyField(blank=True, to='school.Professeur'),
        ),
        migrations.AddField(
            model_name='classe',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_sections', to='school.section'),
        ),
    ]
